/*============================================================================================
 * FILE NAME:            ultrasonic.h
 * AUTHER :              MAHMOUD METWALY
 * DATE CREATED :        12/10/2022
 * DESCRIPTION :         Header File For ultrasonic Driver

 ===========================================================================================*/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*---------------------------------- INCLUDES -------------------------------*/
#include "std_types.h"

/*--------------------------------  DEFINATION -----------------------------*/
#define TRIG_PORT_ID       PORTB_ID
#define TRIG_PIN_ID        PIN5_ID

/*------------------------------ FUNCTION DECLARATION -----------------------*/
/*
 * [Function Name] : Ultrasonic_init()
 * [Description]   : Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
      GPIO driver.
 *[ARG]            :  No ARG
 *
 * [Return]        : Void
 */
void Ultrasonic_init(void);
/*
 * [Function Name] : Ultrasonic_Trigger()
 * [Description]   : Send the Trigger pulse to the ultrasonic.
 *[ARG]            :  No ARG
 *
 * [Return]        : Void
 */
void Ultrasonic_Trigger(void);
/*
 * [Function Name] : Ultrasonic_readDistance()
 * [Description]   : Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 *[ARG]            :  No ARG
 *
 * [Return]        : the Distance in cm
 */
uint16 Ultrasonic_readDistance(void);
/*
 * [Function Name] : Ultrasonic_edgeProcessing()
 * [Description]   : This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
      the ultrasonic sensor
 *[ARG]            :  No ARG
 *
 * [Return]        : Void
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
